### PR TITLE
Added Curium/CRU

### PR DESCRIPTION
**Pull request by mrmetech**

### CODE REVIEW

**Comment by cipig** [comment]
Please do a swap and post the "SWAP completed"-message from bob with the txids, else we can't know if that is working.

**Comment by mrmetech** [comment]
@cipig could tell me how to do that am not familiar with the process

**Comment by cipig** [comment]
You would need two nodes, setup the wallet on both, add the coin to the config and try a swap. But i had a look at the wallet code from https://github.com/curiumofficial/curium myself and couldn't find BIP65 (https://github.com/bitcoin/bips/blob/master/bip-0065.mediawiki) implemented. BarterDEX needs this BIP in order to do atomic swaps. Without it, it will not work. Sorry.

**Comment by mrmetech** [comment]
You guys have coins with this bip so ? how doe that work most of the coins actually.

**Comment by mrmetech** [comment]
And we are based off pivx so how doe that work btw?

**Pull request closed without merging**
