### PR TITLE
Add Stratis Coin

### PR DESCRIPTION
**Pull request by D3m0nKingx**
Wishing to bring Stratis on board with Komodo's BarterDEX, for the time being this should work fine with the c++ daemon (https://github.com/stratisproject/stratisX), until the Stratis team completes the work on the C# NODE (as the RPC api isn't complete as of yet). 

Let me know if anything needs to be done to complete this merge.

### CODE REVIEW

**Comment by cipig** [comment]
stratisX is missing 2 API-calls needed by BarterDEX: gettxout and importaddress

**Comment by dangershony** [comment]
Hi @cipig, your comment implies you are using the built in wallet of the QT is that correct?

**Comment by dangershony** [comment]
>I don't use Stratis  

I am aware of that, the two RPC methods you are asking for `gettxout` and `importaddress` a wallet related RPC methods, this implies you relay on the built in wallet of the a QT (for other clones).

We don't have them on stratisX and not sure we will.

dotnet core is now cross reference so its fairly easy to run the node in linux, not that much to do just apt-get netcore, clone the repo and run the node. however we probably dont have those RPC methods either on the C# node as we use an HD wallet.

**Comment by D3m0nKingx** [comment]
@dangershony @cipig, I just spent some time perusing the code, and it seems that stratisX is using the RPC method `gettransaction` in place of `gettxout`. 

This is the output of that command:

```bash
07:42:50
￼
gettransaction 085f19ca56e40343c1d9578cc9aa57cfd4271f946d2260cd3b821b269da8e227


07:42:50
￼
{
"txid" : "085f19ca56e40343c1d9578cc9aa57cfd4271f946d2260cd3b821b269da8e227",
"version" : 1,
"time" : 1522679772,
"locktime" : 780878,
"vin" : [
{
"txid" : "bcaa4d3fec6497c6f387be780ba8cb72bec832726d6714d1606bed0747066178",
"vout" : 2,
"scriptSig" : {
"asm" : "3044022003df45e526aec188e1fb8377a27edb518ad3e60bb438810126fddfac4284fe2502204d04749aa69e27b1cb43945d5d96a140ea84ce2c05582377b4915a7359a9476601",
"hex" : "473044022003df45e526aec188e1fb8377a27edb518ad3e60bb438810126fddfac4284fe2502204d04749aa69e27b1cb43945d5d96a140ea84ce2c05582377b4915a7359a9476601"
},
"sequence" : 4294967294
}
],
"vout" : [
{
"value" : 139.63990000,
"n" : 0,
"scriptPubKey" : {
"asm" : "OP_DUP OP_HASH160 a4b26492e7592a63bf0cebeabd37742319932522 OP_EQUALVERIFY OP_CHECKSIG",
"hex" : "76a914a4b26492e7592a63bf0cebeabd3774231993252288ac",
"reqSigs" : 1,
"type" : "pubkeyhash",
"addresses" : [
"ScJqZFnN5uV4mJyyxWjsv1yPCRXRQUWR3C"
]
}
},
{
"value" : 5.00000000,
"n" : 1,
"scriptPubKey" : {
"asm" : "OP_DUP OP_HASH160 3f93b440fcc85ff217bebde61794de549850c8d9 OP_EQUALVERIFY OP_CHECKSIG",
"hex" : "76a9143f93b440fcc85ff217bebde61794de549850c8d988ac",
"reqSigs" : 1,
"type" : "pubkeyhash",
"addresses" : [
"ST6AYb7vRVcYZa55yBomiQ8GdFP1Zo7tab"
]
}
}
],
"amount" : 5.00000000,
"confirmations" : 25592,
"blockhash" : "9f04f63eb1683549c4fdf0ffb5e59a7c78da386f998b45c8ccc972e7c2e94bad",
"blockindex" : 2,
"blocktime" : 1522679808,
"txid" : "085f19ca56e40343c1d9578cc9aa57cfd4271f946d2260cd3b821b269da8e227",
"time" : 1522679808,
"timereceived" : 1522680292,
"details" : [
{
"account" : "",
"address" : "ST6AYb7vRVcYZa55yBomiQ8GdFP1Zo7tab",
"category" : "receive",
"amount" : 5.00000000
}
]
}

```

**Comment by satindergrewal** [comment]
closing this request. all coin add requests must go to https://github.com/jl777/coins now.
Also https://github.com/KomodoPlatform/BarterDEX/blob/dev/assets/coins.json is now will always be this static file.
@cipig @himu007 @siulynot please don't add or accept any coin add request to this file.

**Pull request closed without merging**
