### PR TITLE
Adding Rapture electrum server

### PR DESCRIPTION
**Pull request by RaptureCore**
Added Rapture electrum server to electrum_list.js

### CODE REVIEW

**Comment by cipig** [comment]
every coin needs 2 different electrum servers, because of the builtin SPV validation

**Comment by RaptureCore** [comment]
Ok! I'll get a second up and running and then update. Thanks!

**Comment by RaptureCore** [comment]
Second Rapture electrum server up and running, electrum_list.js updated

**Comment by cipig** [comment]
i close this PR, since it is now all in BarterDEX dev + coins db repo

**Pull request closed without merging**
