### PR TITLE
add WAVI

### PR DESCRIPTION
**Pull request by 00uknownUser00**
https://github.com/wavidev-the-man/wavi
http://explorer.wavicom.info

### CODE REVIEW

**Comment by cipig** [comment]
Have you done a swap with WAVI and could post the "SWAP completed"-message from mm?
I don't think confpath can be correct, since every coins-datadir under Linux start with a ., so it could be more like: USERHOME/.WaviCore/wavi.conf

**Comment by 00uknownUser00** [comment]
SWAP completed! 2869526595-2796935730 {"uuid":"f6c465f7f34b035cbbca14f08d3926332e144ba3dbd5e23aac8e5a9ba8b5ade5","expiration":1529105195,"tradeid":0,"requestid":2869526595,"quoteid":2796935730,"iambob":1,"Bgui":"simplegui","Agui":"","gui":"simplegui","bob":"WAVI","srcamount":0.31660824,"bobtxfee":0.00010000,"alice":"KMD","destamount":0.31609806,"alicetxfee":0.00001000,"aliceid":"17681685105327800323","sentflags":["alicespend", "bobspend", "bobpayment", "alicepayment", "bobdeposit", "bobrefund"],"values":[0.31670825, 0.31610805, 0.31680825, 0.31611806, 0.35638428, 0, 0, 0.35628428, 0, 0, 0],"result":"success","status":"finished","finishtime":1529090227,"bobdeposit":"8bd5567a8cec1f769d6da18566fcbe0630825c67cca6df7a4a643d59f5153063","alicepayment":"731d3c9be65f5cb0e1f924640c2b0152b539af29d70d7715c2f8ea3e1fd6ced2","bobpayment":"b2a32eb519ced384b8eb3e6b89069bd2a86aee84b31147ff3ee0d05cea0121ea","paymentspent":"7756e76e94e0edbe65e4bc54486efd13d4bf5762d4c3072d0cbb2b7ebfb1bb3e","Apaymentspent":"6aa759a438dae5d1213552e63f20c393139b04755f0aa6c934e4171fe035600c","depositspent":"3a3ca5c9de78cdceee5d058c4505c0e0160c3997088f6bdb44fcec1c1064dfac","method":"tradestatus","finishtime":1529090227}

> I don't think confpath can be correct, since every coins-datadir under Linux start with a ., so it could be more like: USERHOME/.WaviCore/wavi.conf

im running  windows

**Comment by cipig** [comment]
thanks, looks good. I made a PR for adding WAVI: https://github.com/jl777/coins/pull/90
This is our new repo for coin configs and BarterDEX GUI will use this from now on (currently coinsdb-branch)

**Comment by cipig** [comment]
i close this PR, since it is now all in BarterDEX dev + coins db repo

**Pull request closed without merging**
