### PR TITLE
Needs HODLC as token

### PR DESCRIPTION
**Pull request by FreeTrade**

### CODE REVIEW

**Comment by cipig** [comment]
This shouldn't be needed any more, did a change yesterday regarding this.

**Comment by FreeTrade** [comment]
Can you elaborate on the change you made and let me know if you've tested adding HOdlcoin while using BarterDex. From my tests, using HODLC definitely does work.

**Comment by FreeTrade** [comment]
Also I move HOdlcoin into the cryptocoin category, as it is primarily a  coin.

**Comment by cipig** [comment]
i fixed the coin symbol as you did and later moved HOdlcoin to the coins-section too... do a git pull now (v0.8) and you should have the exact same result

**Comment by FreeTrade** [comment]
Perfect! thank you

**Pull request closed without merging**
