### PR TITLE
Add GalaxyCash

### PR DESCRIPTION
**Pull request by galaxycash**

### CODE REVIEW

**Comment by galaxycash** [comment]
Website: https://galaxycash.info
Github: https://github.com/galaxycash/galaxycash

**Comment by cipig** [comment]
could you please do a swap and post the `SWAP completed!` message from marketmaker that contains the transaction ids?

**Comment by galaxycash** [comment]
Deposits and orders working fine, but i can't check swap, how long need wait for electrum based deposits before place orders?

**Comment by cipig** [comment]
there are no electrum-servers for this coin, not afaik, at least there are no electrum-servers configured in the GUI. To be able to setup electrum-servers the coin has to be added to https://github.com/kyuupichan/electrumx
I wouldn't use electrum for the initial test of a new coin, first check if it swaps with native.

**Comment by galaxycash** [comment]
I use electrum for others coins, not for GCH, after deposits to electrum wallets(DGB, DOGE) i can't place buy orders.

**Comment by cipig** [comment]
electrum may take some time to update the data, but not more then a minute or 2

**Comment by satindergrewal** [comment]
closing this request. all coin add requests must go to https://github.com/jl777/coins now.
Also https://github.com/KomodoPlatform/BarterDEX/blob/dev/assets/coins.json is now will always be this static file.
@cipig @himu007 @siulynot please don't add or accept any coin add request to this file.

**Pull request closed without merging**
