### PR TITLE
Add DAI token (https://makerdao.com)

### PR DESCRIPTION
**Pull request by hanzac**
It's also popular stable coin similar to USDT.

### CODE REVIEW

**Comment by cipig** [comment]
Please test a swap and do the PR in dev-branch, master is only for releases and merging things in master often leads to merge conflicts when someone wants to prepare for a new release.

**Comment by hanzac** [comment]
It can't show the tx for ethereum, is there any requirement for it to get ethereum work? Do I have to install an external ethereum client?

**Comment by TheComputerGenie** [comment]
That error is a logging issue that can be dealt with by commenting out dex_SimpleActions.js#L993

**Comment by satindergrewal** [comment]
closing as it's going to master.
please use `dev` branch next time.

**Comment by cipig** [comment]
did a swap myself
`SWAP completed! 1658943900-1630097863 {"uuid":"33a425becc7bfb4b6fa27f4d0a6ca715b22083744dd00f71c1d8f4cf284c88af","expiration":1527220681,"tradeid":0,"requestid":1658943900,"quoteid":1630097863,"iambob":1,"Bgui":"nogui","Agui":"","gui":"nogui","bob":"DAI","bobtomic":"0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359","etomicsrc":"0x4e623b150b847da59f064f7c7fcc9f787dae2229","srcamount":0.67446483,"bobtxfee":0.00001000,"alice":"KMD","etomicdest":"0xdf38dd108bab50da564092ad0cd739c4634d963c","destamount":0.08009000,"alicetxfee":0.00001000,"aliceid":"12360131572634222593","sentflags":["alicespend", "bobspend", "bobpayment", "alicepayment", "bobdeposit", "bobrefund"],"values":[0.67447483, 0.08010000, 0.67448483, 0.08011000, 0.75879293, 0, 0, 0.75878293, 0, 0, 0],"result":"success","status":"finished","finishtime":1527206148,"bobdeposit":"4c5de02487dc4ecc3891b738b2df5c5400a787c92e4cafa8dba09fea21184c1d","alicepayment":"2defdad61cf8c3302a66b0351efafc4d2a8cfdec3abb1a03ea592c2679c60d22","bobpayment":"46114111a4259514d0b05026cac8de2ec5782d014f8cc1910a3e17b43399571d","paymentspent":"da7141483b7d02841e7d574f7a0c4fb16e96f8ed7d7f1e314f48ef732a088e7b","Apaymentspent":"13b53302876509515d355a2f97f1c239bb5c7edac547dad17159df3db544494d","depositspent":"1b51f73683e2de3667562db18063cbc13d778e4315f4158a8672b761b199d95e","method":"tradestatus","finishtime":1527206148}`
and added it to GUI and coins repo, so i close this PR

**Pull request closed without merging**
